version: "3.7"
services:
  database:
    image: "mysql:8.0"
    container_name: mysql_db
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - /var/lib/mysql
